version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: warmhouse-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: warmhouse
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - warmhouse-network

  temperature-app:
    build:
      context: ./main
      dockerfile: Dockerfile
    container_name: warmhouse
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@warmhouse-postgres:5432/warmhouse
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - warmhouse-network

volumes:
  postgres_data:

networks:
  warmhouse-network:
    driver: bridge